language: php
php:
  - '7.0'
  - '7.1'
# Use the faster container based infrastructure.
sudo: false
before_install:
  - "export DISPLAY=:99.0"
  - "export APPLITOOLS_BATCH_ID=`echo $TRAVIS_COMMIT`"
  - "sh -e /etc/init.d/xvfb start"
install:
  - "composer install"